package com.example.persistence.entities;
// Generated Apr 6, 2024, 1:11:40 AM by Hibernate Tools 6.0.2.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Jobopening generated by hbm2java
 */
@Entity
@Table(name="jobopening"
    ,catalog="hrapi"
)
public class Job implements java.io.Serializable {


     private Integer jobId;
     private Department department;
     private String jobName;
     private String requirements;

    public Job() {
    }

    public Job(Department department, String jobTitle, String requirements) {
       this.department = department;
       this.jobName = jobTitle;
       this.requirements = requirements;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="JobID", unique=true, nullable=false)
    public Integer getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DepartmentID")
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }

    
    @Column(name="JobTitle", length=100)
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    
    @Column(name="Requirements", length=65535)
    public String getRequirements() {
        return this.requirements;
    }
    
    public void setRequirements(String requirements) {
        this.requirements = requirements;
    }




}


