package com.example.persistence.entities;
// Generated Apr 6, 2024, 1:11:40 AM by Hibernate Tools 6.0.2.Final


import com.example.persistence.enums.LeaveStatus;
import com.example.persistence.enums.LeaveType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Date;

/**
 * Leavemanagement generated by hbm2java
 */
@Entity
@Table(name="leavemanagement"
    ,catalog="hrapi"
)
public class LeaveManagement implements java.io.Serializable {


     private Integer leaveId;
     private Employee employee;
     private LeaveType leaveType;
     private Date startDate;
     private Date endDate;
     private LeaveStatus status;
     private Date approvalDate;

    public LeaveManagement() {
    }

    public LeaveManagement(Employee employee, LeaveType leaveType, Date startDate, Date endDate, LeaveStatus status, Date approvalDate) {
       this.employee = employee;
       this.leaveType = leaveType;
       this.startDate = startDate;
       this.endDate = endDate;
       this.status = status;
       this.approvalDate = approvalDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="LeaveID", unique=true, nullable=false)
    public Integer getLeaveId() {
        return this.leaveId;
    }
    
    public void setLeaveId(Integer leaveId) {
        this.leaveId = leaveId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EmployeeID")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="LeaveType", length=8)
    public LeaveType getLeaveType() {
        return this.leaveType;
    }
    
    public void setLeaveType(LeaveType leaveType) {
        this.leaveType = leaveType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="StartDate", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EndDate", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="Status", length=9)
    public LeaveStatus getStatus() {
        return this.status;
    }
    
    public void setStatus(LeaveStatus status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ApprovalDate", length=10)
    public Date getApprovalDate() {
        return this.approvalDate;
    }
    
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }




}


