package com.example.persistence.entities;
// Generated Apr 6, 2024, 1:11:40 AM by Hibernate Tools 6.0.2.Final


import com.example.persistence.enums.PerformanceReating;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Date;

/**
 * Performancereview generated by hbm2java
 */
@Entity
@Table(name="performancereview"
    ,catalog="hrapi"
)
public class PerformanceReview implements java.io.Serializable {


     private Integer reviewId;
     private Employee employee;
     private Date reviewDate;
     private PerformanceReating performanceRating;

    public PerformanceReview() {
    }

    public PerformanceReview(Employee employee, Date reviewDate, PerformanceReating performanceRating) {
       this.employee = employee;
       this.reviewDate = reviewDate;
       this.performanceRating = performanceRating;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ReviewID", unique=true, nullable=false)
    public Integer getReviewId() {
        return this.reviewId;
    }
    
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EmployeeID")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ReviewDate", length=10)
    public Date getReviewDate() {
        return this.reviewDate;
    }
    
    public void setReviewDate(Date reviewDate) {
        this.reviewDate = reviewDate;
    }

    
    @Column(name="PerformanceRating", length=9)
    public PerformanceReating getPerformanceRating() {
        return this.performanceRating;
    }
    
    public void setPerformanceRating(PerformanceReating performanceRating) {
        this.performanceRating = performanceRating;
    }




}


